config/routes.rb
Rails.application.routes.draw do

  resources :rates
  resources :containers
  resources :maersk_tariffs
  resources :regions
  resources :networks
  resources :seaports

  resources :companies do
    resources :lines, shallow: true do
      resources :points, shallow: true
    end
  end

  resources :lines do
    resources :fesco_ints
  end

  root 'seaports#index'


  # API
  namespace :api do
    namespace :v1 do
      namespace :tariffs do
        resources :pols, only: [:index, :show] do
          resources :pods, only: [:index, :show] do
            resources :containers, only: [:index, :show]
          end
        end
      end
      # get 'tariffs/:company', to: 'tariffs#show'
      # get 'tariffs/:company/pols', to: 'pol_tariffs#index'
      # get 'tariffs/:company/pols/:code', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code/containers', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code/containers/:code', to: 'fesco_pol_pod_tariffs#index'
      resources :seaports, only: [:index, :show]
      resources :search_suggestions, only: [:index]
    end
  end


  # resources :fesco_ints do
  #   resources :fesco_int_rates
  # end
  resources :tariffs
end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :company
  belongs_to :maersk_tariff

  has_many :fesco_ints
  has_many :points, -> { order(:number) }
  has_many :seaports, :through => :points

  validates_presence_of :name, :code
  validates_uniqueness_of :code, scope: [:company_id]

  def generate_number
    return 1 if points.last.nil?
    points.last.number + 1
  end

  def code_name
    "#{code} #{name}"
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_company, only: [:create, :new, :index]
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  def index
    @lines = @company.lines
  end

  def show
  end

  def edit
  end

  def new
    @line = @company.lines.new
  end

  def create
    @line = @company.lines.build(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, notice: 'Line was not created' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line.company }
      else
        format.html { render :edit, notice: 'Line was not updated.' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @line.destroy
    redirect_to @line.company, notice: 'Line was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:company_id])
    end

    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:name, :code, :content, :network, :maersk_tariff_id)
    end

end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_fesco_tariff.html.slim
.row 
  .columns.small-12
    h3 Tarrifs
.row 
  .columns.small-12
    table
      thead
        tr
          td POLs
          td PODs
          td Description
          td Manage
      tbody
        - @line.fesco_ints.each do |fesco_int|
          tr
            td
              ul.no-bullet
                - fesco_int.pols.each do |p|
                  li= Seaport.find_by(code: p).name
            td
              ul.no-bullet
                - fesco_int.pods.each do |p|
                  li= Seaport.find_by(code: p).name
            td
              = render('/fesco_ints/table_fesco_int_tariffs', fesco_int: fesco_int)
            td
              ul
                li= link_to 'Show', line_fesco_int_path(@line, fesco_int)
                li= link_to 'Edit', edit_line_fesco_int_path(@line, fesco_int)
                li= link_to 'Destroy', line_fesco_int_path(@line, fesco_int), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/lines/_form.html.haml
= form_for [@company, @line] do |f|
  - if @line.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line.errors.count, "error")} prohibited this line from being saved:"
      %ul
        - @line.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :content
    = f.text_area :content, rows: 15
  .field
    = f.collection_select :maersk_tariff_id, MaerskTariff.all.order('code ASC'), :id, :code, {}, {class: 'select2'}
  .actions
    = f.submit 'Save'

app/views/lines/_point.html.slim
h3 Points
table
  thead
    tr
      th Number
      th Seaport
      th Eta
      th Ets
      th Discharge
      th Load
      th Transit time
      th
      th
      th

  tbody
    - @line.points.each do |point|
      tr
        td= point.number
        td= point.seaport
        td= point.eta
        td= point.ets
        td= point.discharge
        td= point.load
        td= point.transit_time
        td= link_to 'Show', point
        td= link_to 'Edit', edit_point_path(point)
        td= link_to 'Destroy', point, :method => :delete, :data =>   confirm=('Are you sure?' ) 

app/views/lines/_tariffs.html.slim
h3 Tariffs
table
  thead
    tr
      th Trade
      th Currency
      th 20DV
      th 40DV
      th 40HC
      th 45HC
      th 20REEF
      th 40REEF
  tbody
    tr
      td= "#{maersk_tariff.from_region_names} to #{maersk_tariff.to_region_names} (#{maersk_tariff.code} - #{maersk_tariff.from_region_codes} to #{maersk_tariff.to_region_codes})"
      td= maersk_tariff.currency
      th= maersk_tariff.rates.find_by(container_id: Container.find_by(code: '20DV')).try(:sbf)
      Th= maersk_tariff.rates.find_by(container_id: Container.find_by(code: '40DV')).try(:sbf)
      th= maersk_tariff.rates.find_by(container_id: Container.find_by(code: '40HC')).try(:sbf)
      th= maersk_tariff.rates.find_by(container_id: Container.find_by(code: '45HC')).try(:sbf)
      th= maersk_tariff.rates.find_by(container_id: Container.find_by(code: '20REEF')).try(:sbf)
      th= maersk_tariff.rates.find_by(container_id: Container.find_by(code: '40REEF')).try(:sbf)

app/views/lines/edit.html.haml
%h1 Editing line

= render 'form'

= link_to 'Show', @line
\|
= link_to 'Back', company_path(@line.company)

app/views/lines/index.html.haml
%h1 Listing lines

%table
  %tr
    %th Name
    %th Code
    %th
    %th
    %th

  - @lines.each do |line|
    %tr
      %td= line.name
      %td= line.code
      %td= link_to 'Show', line
      %td= link_to 'Edit', edit_line_path(line)
      %td= link_to 'Destroy', line, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Line', new_company_line_path(@company)

app/views/lines/new.html.haml
%h1 New line

= render 'form'

= link_to 'Back', company_lines_path(@company)

app/views/lines/show.html.slim
.row 
  .columns.small-12
    ul.breadcrumbs
      li= link_to "Home", root_path
      li= link_to @line.company.try(:name), company_path(@line.company)
      li.current= @line.name
.row 
  .columns.small-12
    ul.menu
      li
        h4= "Line: #{@line.name} (#{@line.code})"
      li= link_to 'Edit', edit_line_path(@line)
      li= link_to 'Add Tariff', new_line_fesco_int_path(@line) if @line.company.code == 'fesco'
.row 
  .columns.small-12
    = markdown @line.content
    .button-group
      = link_to 'Show Points', line_points_path(@line), class: 'button secondary'
      = link_to 'Add a Point', new_line_point_path(@line), class: 'button'

    
= render "point" if @line.points.any?

= render "tariffs", maersk_tariff: @line.maersk_tariff if @line.maersk_tariff

- if @line.company.code == 'fesco'
  = render "fesco_tariff"