config/routes.rb
Rails.application.routes.draw do

  resources :rates
  resources :containers
  resources :maersk_tariffs
  resources :regions
  resources :networks
  resources :seaports

  resources :companies do
    resources :lines, shallow: true do
      resources :points, shallow: true
    end
  end

  resources :lines do
    resources :fesco_ints
  end

  root 'seaports#index'


  # API
  namespace :api do
    namespace :v1 do
      namespace :tariffs do
        resources :pols, only: [:index, :show] do
          resources :pods, only: [:index, :show] do
            resources :containers, only: [:index, :show]
          end
        end
      end
      # get 'tariffs/:company', to: 'tariffs#show'
      # get 'tariffs/:company/pols', to: 'pol_tariffs#index'
      # get 'tariffs/:company/pols/:code', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code/containers', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code/containers/:code', to: 'fesco_pol_pod_tariffs#index'
      resources :seaports, only: [:index, :show]
      resources :search_suggestions, only: [:index]
    end
  end


  # resources :fesco_ints do
  #   resources :fesco_int_rates
  # end
  resources :tariffs
end

app/models/container.rb
class Container < ActiveRecord::Base
  validates :code, uniqueness: { case_sensitive: false }
end

app/controllers/api/v1/tariffs/containers_controller.rb
class Api::V1::Tariffs::ContainersController < ApplicationController
  before_action :set_pol
  before_action :set_pod
  before_action :set_container, only: [:show]

  def index
    @tariffs = {}

    @tariffs[:tariffs] = FescoIntTariff.get_all_redis([@pol], [@pod]).reject { |c| c.empty? }

    render json: @tariffs
  end

  def show
    @tariffs = {}

    @tariffs[:tariffs] = FescoIntTariff.get_all_redis([@pol],[@pod],[@container]).reject { |c| c.empty? }
    

    render json: @tariffs
  end
  
  private

  def set_pol
    @pol = params[:pol_id].upcase
  end

  def set_pod
    @pod = params[:pod_id].upcase
  end

  def set_container
    @container = params[:id].upcase
  end

end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: [:show, :edit, :update, :destroy]

  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
  end

  # GET /containers/new
  def new
    @container = Container.new
  end

  # GET /containers/1/edit
  def edit
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(container_params)

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1
  # PATCH/PUT /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_url, notice: 'Container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params.require(:container).permit(:code, :name, :category, :description)
    end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_form.html.erb
<%= form_for(@container) do |f| %>
  <% if @container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% @container.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editing Container</h1>

<%= render 'form' %>

<%= link_to 'Show', @container %> |
<%= link_to 'Back', containers_path %>

app/views/containers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Containers</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Category</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @containers.each do |container| %>
      <tr>
        <td><%= container.code %></td>
        <td><%= container.name %></td>
        <td><%= container.category %></td>
        <td><%= container.description %></td>
        <td><%= link_to 'Show', container %></td>
        <td><%= link_to 'Edit', edit_container_path(container) %></td>
        <td><%= link_to 'Destroy', container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Container', new_container_path %>

app/views/containers/new.html.erb
<h1>New Container</h1>

<%= render 'form' %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @container.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @container.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @container.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @container.description %>
</p>

<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>