config/routes.rb
Rails.application.routes.draw do

  resources :rates
  resources :containers
  resources :maersk_tariffs
  resources :regions
  resources :networks
  resources :seaports

  resources :companies do
    resources :lines, shallow: true do
      resources :points, shallow: true
    end
  end

  resources :lines do
    resources :fesco_ints
  end

  root 'seaports#index'


  # API
  namespace :api do
    namespace :v1 do
      namespace :tariffs do
        resources :pols, only: [:index, :show] do
          resources :pods, only: [:index, :show] do
            resources :containers, only: [:index, :show]
          end
        end
      end
      # get 'tariffs/:company', to: 'tariffs#show'
      # get 'tariffs/:company/pols', to: 'pol_tariffs#index'
      # get 'tariffs/:company/pols/:code', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code/containers', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code/containers/:code', to: 'fesco_pol_pod_tariffs#index'
      resources :seaports, only: [:index, :show]
      resources :search_suggestions, only: [:index]
    end
  end


  # resources :fesco_ints do
  #   resources :fesco_int_rates
  # end
  resources :tariffs
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :lines
  validates_presence_of :name, :code

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    if params[:line_id]
      @line = @company.lines.find(params[:line_id])
    else
      @line = Line.new
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :code, :web, :content, :logo)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :web
    = f.text_field :web
  .field
    = f.label :content
    = f.text_area :content, rows: 20
  .field
    = f.label :logo
    = f.text_field :logo
  .actions
    = f.submit 'Save'

app/views/companies/_line.html.slim
.panel
  ul.menu
    li
      h3= "#{line.name} (#{line.code})"
    li= link_to 'Edit', edit_line_path(line)
    li= link_to 'Destroy', line_path(line), :method => :delete, :data => { :confirm => 'Are you sure?' }
    li= link_to 'Show', line_path(line)
        

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %tr
    %th Name
    %th Code
    %th Web
    %th Logo
    %th
    %th
    %th

  - @companies.each do |company|
    %tr
      %td= company.name
      %td= company.code
      %td= link_to company.web, company.web
      %td= image_tag company.logo, class: "logo th"
      %td= link_to 'Show', company
      %td= link_to 'Edit', edit_company_path(company)
      %td= link_to 'Destroy', company, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
.row 
  .columns.small-12
    %ul.breadcrumbs
      %li= link_to "Home", root_path
      %li= link_to "Companies", companies_path
      %li.current= @company.code

.row
  .columns.small-12.medium-7.large-9
    %h1= @company.name
    %hr
.row
  .columns.small-12.medium-7.large-9
    = markdown @company.content
  .columns.small-12.medium-5.large-3
    %p= image_tag @company.logo, class: "logo th"
    %p= link_to @company.web, @company.web
    %ul.menu
      %li= link_to 'Edit', edit_company_path(@company)
      %li= link_to 'Back', companies_path

.row
  .columns.small-12
    - if @company.lines.any?
      %h3 Lines
      %hr
      - @company.lines.each do |line|
        = render 'line', line: line

.row
  .columns.small-12
    = link_to "Add New Line", new_company_line_path(@company), class: "button"