config/routes.rb
Rails.application.routes.draw do

  resources :rates
  resources :containers
  resources :maersk_tariffs
  resources :regions
  resources :networks
  resources :seaports

  resources :companies do
    resources :lines, shallow: true do
      resources :points, shallow: true
    end
  end

  resources :lines do
    resources :fesco_ints
  end

  root 'seaports#index'


  # API
  namespace :api do
    namespace :v1 do
      namespace :tariffs do
        resources :pols, only: [:index, :show] do
          resources :pods, only: [:index, :show] do
            resources :containers, only: [:index, :show]
          end
        end
      end
      # get 'tariffs/:company', to: 'tariffs#show'
      # get 'tariffs/:company/pols', to: 'pol_tariffs#index'
      # get 'tariffs/:company/pols/:code', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code/containers', to: 'fesco_pol_pod_tariffs#index'
      # get 'tariffs/:company/pols/:code/pods/:code/containers/:code', to: 'fesco_pol_pod_tariffs#index'
      resources :seaports, only: [:index, :show]
      resources :search_suggestions, only: [:index]
    end
  end


  # resources :fesco_ints do
  #   resources :fesco_int_rates
  # end
  resources :tariffs
end

app/models/fesco_int.rb
class FescoInt < ActiveRecord::Base
  belongs_to :line
  has_many :fesco_int_tariffs

  accepts_nested_attributes_for :fesco_int_tariffs, allow_destroy: true

  def self.index_tariffs
    self.find_each do |fi|
      fi.pols.each do |pol|
        $redis.sadd "FESCO:POLS", pol
        fi.pods.each do |pod|
          $redis.sadd "FESCO:PODS", pod
          fi.fesco_int_tariffs.each do |fit|
            fit.containers.each do |container|          
              $redis.sadd "FESCO:containers", container
              $redis.sadd "FESCO:status", fit.status
              $redis.sadd "FESCO:owners", fit.owner
              $redis.hmset "FESCO:#{pol}:#{pod}:#{container}:#{fit.status}:#{fit.owner}",
                           'company',   'FESCO',
                           'pol',       pol,
                           'pod',       pod,
                           'container', container,
                           'status',    fit.status,
                           'owners',    fit.owner,
                           'freight',   fit.freight,
                           'baf',       fit.baf
            end
          end
        end
      end
    end
  end

end

app/controllers/fesco_ints_controller.rb
class FescoIntsController < ApplicationController
  before_action :set_fesco_int, only: [:show, :edit, :update, :destroy]
  before_action :set_seaports, only: [:new, :edit]
  before_action :set_line

  # GET /fesco_ints
  # GET /fesco_ints.json
  def index
    @fesco_ints = FescoInt.all
  end

  # GET /fesco_ints/1
  # GET /fesco_ints/1.json
  def show
    @pols = @fesco_int.pols.map{ |p| Seaport.find_by(code: p).name }
    @pods = @fesco_int.pods.map{ |p| Seaport.find_by(code: p).name }
  end

  # GET /fesco_ints/new
  def new
    @fesco_int = FescoInt.new
    fill_default
  end

  # GET /fesco_ints/1/edit
  def edit
  end

  # POST /fesco_ints
  # POST /fesco_ints.json
  def create
    @fesco_int = FescoInt.new(fesco_int_params)

    respond_to do |format|
      if @fesco_int.save
        format.html { redirect_to line_fesco_int_path(@line, @fesco_int), notice: 'Fesco int was successfully created.' }
        format.json { render :show, status: :created, location: line_fesco_int_path(@line, @fesco_int) }
      else
        format.html { render :new }
        format.json { render json: @fesco_int.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fesco_ints/1
  # PATCH/PUT /fesco_ints/1.json
  def update
    respond_to do |format|
      if @fesco_int.update(fesco_int_params)
        format.html { redirect_to line_fesco_int_path(@line, @fesco_int), notice: 'Fesco int was successfully updated.' }
        format.json { render :show, status: :ok, location: line_fesco_int_path(@line, @fesco_int) }
      else
        format.html { render :edit }
        format.json { render json: @fesco_int.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fesco_ints/1
  # DELETE /fesco_ints/1.json
  def destroy
    @fesco_int.destroy
    respond_to do |format|
      format.html { redirect_to line_url(@line), notice: 'Fesco int was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_line
      @line = Line.find(params[:line_id])
    end

    def set_fesco_int
      @fesco_int = FescoInt.find(params[:id])
    end

    def set_seaports
      @seaports = Seaport.all.map{|p| [p.name, p.code]}
    end

    def fesco_int_params
      params[:fesco_int][:pols] = params[:fesco_int][:pols].reject{|a| a.empty?}
      params[:fesco_int][:pods] = params[:fesco_int][:pods].reject{|a| a.empty?}
      params.require(:fesco_int).permit(:line_id, :pols => [], :pods => [], :fesco_int_tariffs_attributes => [ :id, :status, :owner, :freight, :baf, :_destroy, :containers => [] ])
    end

    def fill_default
      @fesco_int.fesco_int_tariffs.new(status: "Empty", owner: "SOC", containers: ["20'"])
      @fesco_int.fesco_int_tariffs.new(status: "Empty", owner: "SOC", containers: ["40'", "40'HC"])
      @fesco_int.fesco_int_tariffs.new(status: "Full", owner: "COC", containers: ["20'DC"])
      @fesco_int.fesco_int_tariffs.new(status: "Full", owner: "COC", containers: ["40'", "40'HC"])
      @fesco_int.fesco_int_tariffs.new(status: "Full", owner: "SOC", containers: ["20'DC"])
      @fesco_int.fesco_int_tariffs.new(status: "Full", owner: "SOC", containers: ["40'", "40'HC"])
      @fesco_int.fesco_int_tariffs.new(status: "Full", owner: "SOC", containers: ["20'RF"])
      @fesco_int.fesco_int_tariffs.new(status: "Full", owner: "SOC", containers: ["40'RF"])
    end
end

app/helpers/fesco_ints_helper.rb
module FescoIntsHelper
end

app/views/fesco_ints/_fesco_int_tariff_fields.html.slim
.row.fesco_int_tariff
  .large-2.columns
    = f.select :status, ["Full", "Empty"]
  .large-2.columns
    = f.select :owner, ["SOC","COC"]
  #containers.large-3.columns
    = f.select :containers, ["20'", "20'DC", "20'RF", "40'", "40'HC", "40'RF"], {prompt: ""}, {multiple: true, class: "select2"}
  .large-2.columns
    = f.text_field :freight
  .large-2.columns
    = f.text_field :baf
  .large-1.columns
    = f.hidden_field :_destroy
    = link_to "Remove", '#', class: "remove_fields"

app/views/fesco_ints/_form.html.slim
= form_for [@line, @fesco_int] do |f|
  - if @fesco_int.errors.any?
    #error_explanation
      h2= "#{pluralize(@fesco_int.errors.count, "error")} prohibited this fesco_int from being saved:"
      ul
        - @fesco_int.errors.full_messages.each do |msg|
          li= msg
  .row
    = f.hidden_field :line_id, value: @line.try(:id)
    .large-6.columns
      h3 POLS
      = f.select :pols, @seaports, {prompt: ""}, {multiple: true, class: 'select2'}
    .large-6.columns
      h3 PODS
      = f.select :pods, @seaports, {prompt: ""}, {multiple: true, class: 'select2'}

  hr
  .row
    .large-2.columns
      p Status
    .large-2.columns
      p Owner
    .large-3.columns
      p Containers
    .large-2.columns
      p Freight
    .large-2.columns
      p Baf
  .row
    .large-12.columns
      = f.fields_for :fesco_int_tariffs do |builder|
        = render 'fesco_int_tariff_fields', f: builder
      = link_to_add_fields "Add Tariff", f, :fesco_int_tariffs

  .actions
    = f.submit 'Save'

app/views/fesco_ints/_table_fesco_int_tariffs.html.slim
table
  thead
    tr
      td Status
      td Owner
      td Containers
      td Freight
      td BAF
  tbody
    - fesco_int.fesco_int_tariffs.each do |t|
      tr
        td= t.status
        td= t.owner
        td
          - t.containers.each do |c|
            = "#{c} "
        td= t.freight
        td= t.baf

app/views/fesco_ints/edit.html.haml
%h1 Editing fesco_int

= render 'form'

= link_to 'Show', line_fesco_int_path(@line, @fesco_int)
\|
= link_to 'Back', line_path(@line)

app/views/fesco_ints/index.html.haml
%h1 Listing fesco_ints

%table
  %thead
    %tr
      %th Line
      %th Pols
      %th Pods
      %th Status
      %th Owner
      %th Containers
      %th Freight
      %th Baf
      %th
      %th
      %th

  %tbody
    - @fesco_ints.each do |fesco_int|
      %tr
        %td= fesco_int.line
        %td= fesco_int.pols
        %td= fesco_int.pods
        %td
        %td
        %td
        %td
        %td
        %li= link_to 'Show', line_fesco_int_path(@line, fesco_int)
        %td= link_to 'Edit', edit_line_fesco_int_path(@line, fesco_int)
        %td= link_to 'Destroy', line_fesco_int_path(@line, fesco_int), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

-# = link_to 'New Fesco int', new_fesco_int_path

app/views/fesco_ints/new.html.haml
%h1 New fesco_int

= render 'form'

= link_to 'Back', line_path(@line)

app/views/fesco_ints/show.html.slim
.row 
  .columns.small-12
    ul.breadcrumbs
      li= link_to "Home", root_path
      li= link_to @fesco_int.try(:line).try(:company).try(:name), company_path(@line.company)
      li= link_to @fesco_int.try(:line).try(:name), line_path(@fesco_int.line)
      li.current Tariff

.row 
  .columns.small-11
    p= "Line: #{@fesco_int.line.try(:name)} (#{@fesco_int.line.try(:code)})"
  .columns.small-1
    = link_to 'Edit', edit_line_fesco_int_path(@line, @fesco_int)
 
.row 
  .columns.small-3
    h5 POLS:
    ul.no-bullet
      - @pols.each do |pol|
        li = pol
  .columns.small-3
    h5 PODS:
    ul.no-bullet
      - @pods.each do |pod|
        li = pod
  .columns.small-6
    table
      thead
        tr
          td Status
          td Owner
          td Containers
          td Freight
          td BAF
      tbody
        - @fesco_int.fesco_int_tariffs.each do |t|
          tr
            td= t.status
            td= t.owner
            td
              - t.containers.each do |c|
                = "#{c} "
            td= t.freight
            td= t.baf